/**
 * GAS Template — Master Configuration (CommonJS mirror of gas.config.ts).
 *
 * Node-evaluated build tools (tailwind.config.js, eas-cli) require() this file
 * because they cannot load the TypeScript gas.config.ts. It carries the FULL
 * config so it is safe even if Metro resolves it at runtime.
 *
 * Auto-generated by DevAgent — kept in lockstep with gas.config.ts.
 */

const gasConfig = {
  app: {
    name: "Buckets",
    slug: "buckets",
    description: "Replace your sinking fund spreadsheet with a calculator that tells you one number: exactly how much to move this month across every irregular expense, with zero manual math.",
    scheme: "buckets",
    version: "1.0.0",
    minRuntimeVersion: "1.0.0",
    appStoreUrl: "",
    owner: "goodspeed_app_studio",
  },

  design: {
    mood: "professional",
    colors: {
      text: "#1A1A1A",
      error: "#EF4444",
      accent: "#F59E0B",
      border: "#E5E7EB",
      primary: "#6366F1",
      success: "#10B981",
      surface: "#F9FAFB",
      warning: "#F59E0B",
      textDark: "#F2F2F7",
      secondary: "#8B5CF6",
      background: "#FFFFFF",
      borderDark: "#2C2C2E",
      primaryDark: "#818CF8",
      surfaceDark: "#1C1C1E",
      textSecondary: "#6B7280",
      backgroundDark: "#0F0F0F",
      textSecondaryDark: "#9CA3AF",
    },
    typography: {
      bodyFont: "Inter",
      monoFont: "none",
      displayFont: "Inter",
      headingWeight: "700",
    },
    layout: {
      spacing: "comfortable",
      cardStyle: "outlined",
      buttonStyle: "rounded",
      borderRadius: "md",
      navigationStyle: "standard",
    },
  },

  features: {
    auth: {
      email: true,
      google: false,
      apple: false,
      twitter: false,
      github: false,
      facebook: false,
      discord: false,
      linkedin: false,
      microsoft: false,
      spotify: false,
      slack: false,
      twitch: false,
      notion: false,
      figma: false,
      biometric: {
        enabled: false,
        timeoutMinutes: 5,
      },
      magicLink: false,
      guestMode: false,
      mfa: false,
    },
    pushNotifications: {
      enabled: false,
      permissionTiming: "onboarding",
      channels: ["default"],
    },
    inAppPurchases: {
      enabled: true,
      tiers: [
        {
          name: "Free",
          productId: "free_tier",
          price: "$0",
          features: [
            "Up to 3 active buckets",
            "Auto-calculated monthly set-aside per bucket",
            "Unified monthly total dashboard",
            "5 pre-built bucket templates",
            "Manual contribution logging",
            "Progress tracking (arc rings)",
            "Bucket Reset / Archive flow",
            "30-day free trial of Pro (no payment required)",
          ],
        },
        {
          name: "Buckets Pro (Monthly)",
          productId: "buckets_pro_monthly",
          price: "$4.99/month",
          features: [
            "Everything in Free",
            "Unlimited buckets",
            "Paycheck-cycle push notifications",
            "30-day due-date bucket warnings",
            "Monthly summary with contribution history",
            "Contribution history per bucket",
            "Data export (CSV + JSON)",
            "Priority email support",
          ],
          trialDays: 30,
        },
        {
          name: "Buckets Pro (Annual)",
          productId: "buckets_pro_annual",
          price: "$34.99/year",
          features: [
            "Everything in Pro Monthly",
            "42% savings vs. monthly ($2.92/mo equivalent)",
            "Save $24.89 per year vs. monthly billing",
            "Annual plan badge in profile",
          ],
          trialDays: 30,
        },
        {
          name: "Buckets Sync (Future)",
          productId: "buckets_sync_monthly",
          price: "$9.99/month (defined, not built in V1)",
          features: [
            "Everything in Pro Annual",
            "Bank account read-only sync (Plaid)",
            "Automatic contribution detection",
            "Couple / shared bucket mode with split-contribution UI",
            "Multi-device real-time sync",
          ],
        },
      ],
      oneTimePurchases: [],
      credits: {
        enabled: false,
        currencyName: "credit",
        currencyNamePlural: "credits",
        iconName: "Coins",
        packs: [],
      },
      marketplace: {
        enabled: false,
        platformFeePercent: 0,
        sellerPayoutMethod: "stripe_connect",
        listingCategories: [],
        requiresApproval: true,
        escrowEnabled: false,
      },
    },
    analytics: {
      enabled: true,
      provider: "posthog",
      crashReporting: false,
      sessionRecording: false,
      featureFlags: false,
    },
    darkMode: {
      enabled: true,
      default: "system",
    },
    offlineSync: {
      enabled: false,
      cachedEntities: [],
      syncStrategy: "on_reconnect",
      encrypted: false,
    },
    gamification: {
      enabled: false,
      elements: [],
    },
    onboarding: {
      enabled: true,
      steps: ["welcome", "step-2", "step-3", "step-4", "step-5", "step-6"],
    },
    helpSystem: false,
    search: {
      enabled: null,
      entities: null,
      implementation: "client-side",
    },
    socialSharing: {
      enabled: false,
      content: [],
      platforms: [],
    },
    i18n: {
      enabled: false,
      locales: ["en"],
      defaultLocale: "en",
    },
    media: {
      imagePicker: false,
      camera: false,
      audioPlayback: false,
      videoPlayback: false,
      fileUpload: false,
    },
    compliance: {
      attDialog: false,
      gdprConsent: false,
      ccpaNotice: false,
      ageGate: false,
      dataExport: true,
    },
    ads: {
      enabled: false,
      provider: "admob",
    },
    notifications: {
      enabled: false,
      categories: {
        transactional: {
          enabled: true,
          defaultOn: true,
        },
        product: {
          enabled: true,
          defaultOn: true,
        },
        marketing: {
          enabled: true,
          defaultOn: false,
        },
      },
      receiptPolling: {
        enabled: true,
        intervalMinutes: 5,
        expireAfterMinutes: 30,
      },
    },
    telemetry: {
      enabled: true,
      flushIntervalMs: 30000,
      maxQueueSize: 200,
      debugOverlay: false,
      ingestUrl: "https://goodspeed.app/api/telemetry/ingest",
    },
    anonymousAuth: {
      enabled: false,
      tables: [],
    },
    backgroundFetch: false,
    csvExport: false,
    showBuiltWithBadge: false,
  },

  navigation: {
    tabs: [
      {
        id: "dashboard",
        label: "Dashboard (Funds Home)",
        icon: "Home",
        file: "dashboard",
      },
      {
        id: "timeline",
        label: "Timeline View",
        icon: "Calendar",
        file: "timeline",
      },
      {
        id: "contribute",
        label: "Contribute Screen (Tab Center Action)",
        icon: "LayoutGrid",
        file: "contribute",
      },
      {
        id: "settings",
        label: "Settings",
        icon: "Settings",
        file: "settings",
      },
    ],
    hiddenScreens: [],
    modals: ["paywall"],
  },

  backend: {
    supabase: {
      url: "",
      anonKey: "",
    },
  },

  releaseChannels: {
    current: "production",
    storeUrl: {
      ios: "",
      android: "",
    },
  },

  compliance: {
    accountDeletionGracePeriod: {
      days: 30,
    },
    allowImmediateDeletion: true,
    exportTables: [
      "profiles",
      "push_tokens",
      "notifications",
      "user_bookmarks",
      "feedback",
      "consent_log",
    ],
    consentBannerRequired: "eu_only",
  },

  ui: {
    breakpoints: {
      tablet: 600,
      desktop: 1024,
    },
    honorDynamicType: true,
    honorReducedMotion: true,
  },

  multiTenancy: {
    enabled: false,
    defaultRole: "member",
  },

  integrations: {
    oauthProviders: [],
  },

  growth: {
    experimentsEnabled: true,
    defaultBackgroundSyncIntervalMs: 60000,
  },
};

module.exports = { gasConfig };
