-- 003_seed.sql — starter content so the app launches non-empty.
-- Generated deterministically by DevAgent; idempotent (on conflict do nothing).

-- BucketTemplates (bucket_templates)
insert into public.bucket_templates (id, name, icon_key, suggested_amount, smart_date_hint, smart_date_logic, description, sort_order, is_active) values ('c5b0facf-f60e-5f0a-8f85-db4e54b1cc7a', 'Car Registration', 'car', 25, 'Annual — enter your renewal month', '{"frequency":"yearly","default_month":3,"day":1}'::jsonb, 'Spread your annual DMV registration fee into painless monthly contributions so the bill never catches you off guard.', 1, true) on conflict (id) do nothing;
insert into public.bucket_templates (id, name, icon_key, suggested_amount, smart_date_hint, smart_date_logic, description, sort_order, is_active) values ('0c8493db-2432-5c3d-8cc3-5173246d6e8e', 'Holiday Gifts', 'gift', 83, 'Annual — targets December 1st', '{"frequency":"yearly","default_month":12,"day":1}'::jsonb, 'Set a total gift budget and Buckets back-calculates exactly how much to save each month so December feels like a win, not a debt spiral.', 2, true) on conflict (id) do nothing;
insert into public.bucket_templates (id, name, icon_key, suggested_amount, smart_date_hint, smart_date_logic, description, sort_order, is_active) values ('a7998319-370d-53e8-84a8-ae9371d274eb', 'Home Insurance Premium', 'home', 120, 'Annual or semi-annual — enter your due date', '{"frequency":"yearly","default_month":6,"day":1}'::jsonb, 'Whether your insurer bills you once or twice a year, this bucket divides the lump sum across every month so the due date is always fully funded.', 3, true) on conflict (id) do nothing;
insert into public.bucket_templates (id, name, icon_key, suggested_amount, smart_date_hint, smart_date_logic, description, sort_order, is_active) values ('11191af9-7bd1-5354-81d5-81571340033a', 'Quarterly Pest Control', 'bug', 35, 'Every 3 months — enter your next service date', '{"frequency":"quarterly","day":15}'::jsonb, 'Routine pest control visits hit every three months. Save a fixed amount monthly so each invoice is already covered when the technician shows up.', 4, true) on conflict (id) do nothing;
insert into public.bucket_templates (id, name, icon_key, suggested_amount, smart_date_hint, smart_date_logic, description, sort_order, is_active) values ('efa309cb-f009-5db6-807c-0b13af32c6f0', 'Annual Subscriptions', 'subscription', 18, 'Annual — enter the renewal date', '{"frequency":"yearly","day":1}'::jsonb, 'Cloud storage, streaming bundles, software licenses — any subscription billed once a year belongs here so the charge is never a surprise.', 5, true) on conflict (id) do nothing;
insert into public.bucket_templates (id, name, icon_key, suggested_amount, smart_date_hint, smart_date_logic, description, sort_order, is_active) values ('f7746ed5-d240-5179-8af9-90cd2698a311', 'Vet & Pet Care', 'paw', 50, 'Annual checkup — enter your vet appointment month', '{"frequency":"yearly","default_month":4,"day":1}'::jsonb, 'Annual exams, vaccines, and unexpected visits add up fast. Keep a dedicated bucket growing month-to-month so your pet''s health never competes with rent.', 6, true) on conflict (id) do nothing;
insert into public.bucket_templates (id, name, icon_key, suggested_amount, smart_date_hint, smart_date_logic, description, sort_order, is_active) values ('0a880385-cd28-50ec-878c-71e28a36dfd7', 'Car Maintenance', 'wrench', 60, 'Ongoing — funds accumulate for the next oil change or repair', '{"frequency":"ongoing","min_months":3}'::jsonb, 'Tires, oil changes, brake pads — car upkeep is unpredictable but inevitable. Build a rolling cushion so the next mechanic bill comes from savings, not credit.', 7, true) on conflict (id) do nothing;
insert into public.bucket_templates (id, name, icon_key, suggested_amount, smart_date_hint, smart_date_logic, description, sort_order, is_active) values ('600c6eb2-c41a-5fb7-8075-df6b42995cb3', 'Family Vacation', 'airplane', 200, 'One-time goal — enter your travel date', '{"frequency":"one_time"}'::jsonb, 'Enter your trip total and departure date. Buckets tells you exactly how much to set aside each month between now and wheels-up.', 8, true) on conflict (id) do nothing;
